### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by mamiko3** [mamiko3/chat-space#11]
# IPアドレス
18.176.115.226

**Comment by kohei-isoda** [comment]
村上さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◯ サインアップしようとすると以下のエラーが出てしまう
（※ ユーザー名がtest、アドレスがtest@comで登録しようとしました）
[![Screenshot from Gyazo](https://gyazo.com/c5ca907753b89ff2fa93c0db721a88ba/raw)](https://gyazo.com/c5ca907753b89ff2fa93c0db721a88ba)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by mamiko3** [comment]
ご確認ありがとうございます。私の方ではサインアップは通常通りできました。
お手数おかけしますが再度ご確認よろしくお願いします。
gyazoGIF
https://gyazo.com/b200d5c950125fff8187c98508c9306e

**Comment by kohei-isoda** [comment]
ご返信ありがとうございます！
ただやはり何度確認してもユーザー名がtest、アドレスがtest@comで登録しようとすると
エラーが出てしまいます。

エラーが出ないようにバリデーションで弾くようにして頂ければと思います！
（同じメールアドレスは存在しています、など）

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by kohei-isoda** [comment]
村上さん、大変申し訳ございません。

メンターの田中からも連絡があったかと思いますが、
上記の指摘事項に関してはカリキュラムに記載がないためLGTMとさせて頂きます。
（上記以外には不備はございませんでした）

お手数おかけしまして大変申し訳ございませんでした。

**Comment by mamiko3** [comment]
kohei-isoda さん
ご確認とLGTMのご連絡、誠にありがとうございました。
こちらこそ、何度もレビューいただきお手数おかけいたしました。
LGTM、とても嬉しいです。
ありがとうございました。引き続きよろしくお願いいたします！
